name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            images/github-contribution-grid-snake.svg
            images/github-snake-dark.svg?palette=github-dark
            images/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animations
          path: images
